SELECT TOTAL_EMPLOYEE_COUNT, TOTAL_BASE_SALARY, TOTAL_BONUS, (TOTAL_BASE_SALARY + TOTAL_BONUS) AS SUM_TOTAL_SALARY
FROM (
    SELECT
        COUNT(s.EMPLOYEE_KEY) AS TOTAL_EMPLOYEE_COUNT
         ,	SUM(s.BASE_SALARY) AS TOTAL_BASE_SALARY
         ,	SUM(s.BONUS) AS TOTAL_BONUS
    FROM SALARY s
    WHERE s.END_DATE IS NULL
      AND s.BONUS > 0
)
;
