/******************************************************************************************
 DROP
******************************************************************************************/
DROP TABLE IF EXISTS COMPANY CASCADE CONSTRAINTS;
DROP TABLE IF EXISTS DEPARTMENT CASCADE CONSTRAINTS;
DROP TABLE IF EXISTS EMPLOYEE CASCADE CONSTRAINTS;
DROP TABLE IF EXISTS SALARY CASCADE CONSTRAINTS;

DROP INDEX IF EXISTS COMPANY_PK;
DROP INDEX IF EXISTS COMPANY_UK;
DROP INDEX IF EXISTS DEPARTMENT_PK;
DROP INDEX IF EXISTS DEPARTMENT_UK;
DROP INDEX IF EXISTS EMPLOYEE_PK;
DROP INDEX IF EXISTS SALARY_PK;
DROP INDEX IF EXISTS SALARY_UK;
DROP INDEX IF EXISTS SALARY_CURRENT_UK;

DROP SEQUENCE IF EXISTS SEQ_COMPANY_KEY;
DROP SEQUENCE IF EXISTS SEQ_DEPARTMENT_KEY;
DROP SEQUENCE IF EXISTS SEQ_EMPLOYEE_KEY;
DROP SEQUENCE IF EXISTS SEQ_SALARY_KEY;

/******************************************************************************************
 TABLE 및 인덱스 정의
******************************************************************************************/
CREATE TABLE COMPANY(
    COMPANY_KEY NUMBER NOT NULL
,   COMPANY_NAME VARCHAR2(30) NOT NULL
,   BUSINESS_NUMBER CHAR(10) NOT NULL
,   CLOSE_STATUS CHAR(1) NOT NULL
,   ADDRESS VARCHAR2(4000)
,   STATUS VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL
,   NATION_CODE CHAR(3)
,   CREATED_AT TIMESTAMP(3) NOT NULL
,   MODIFIED_AT TIMESTAMP(3) NOT NULL
)
TABLESPACE TSD_COMPANY_DATA
LOGGING
;

CREATE UNIQUE INDEX COMPANY_PK
ON COMPANY(COMPANY_KEY)
TABLESPACE TSD_COMPANY_IDX
;

CREATE UNIQUE INDEX COMPANY_UK
ON COMPANY(BUSINESS_NUMBER)
TABLESPACE TSD_COMPANY_IDX
;

ALTER TABLE COMPANY
ADD CONSTRAINT COMPANY_PK
PRIMARY KEY (COMPANY_KEY)
USING INDEX COMPANY_PK
;

CREATE TABLE DEPARTMENT(
    DEPARTMENT_KEY NUMBER NOT NULL
,   COMPANY_KEY NUMBER NOT NULL
,   DEPARTMENT_ID VARCHAR2(30) NOT NULL
,   DEPARTMENT_NAME VARCHAR2(60) NOT NULL
,   STATUS VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL
,   DESCRIPTION VARCHAR2(1000)
,   CREATED_AT TIMESTAMP(3) NOT NULL
,   MODIFIED_AT TIMESTAMP(3) NOT NULL
)
TABLESPACE TSD_COMPANY_DATA
LOGGING
;

CREATE UNIQUE INDEX DEPARTMENT_PK
ON DEPARTMENT(DEPARTMENT_KEY)
TABLESPACE TSD_COMPANY_IDX
;

CREATE UNIQUE INDEX DEPARTMENT_UK
ON DEPARTMENT(COMPANY_KEY, DEPARTMENT_ID)
TABLESPACE TSD_COMPANY_IDX
;

ALTER TABLE DEPARTMENT
ADD CONSTRAINT DEPARTMENT_PK
PRIMARY KEY (DEPARTMENT_KEY)
USING INDEX DEPARTMENT_PK
;

CREATE TABLE EMPLOYEE(
    EMPLOYEE_KEY NUMBER NOT NULL
,   EMPLOYEE_NO VARCHAR2(20) NOT NULL
,   EMPLOYEE_NAME VARCHAR2(100) NOT NULL
,   DEPARTMENT_KEY NUMBER NOT NULL
,   POSITION_CODE VARCHAR2(20)
,   HIRE_DATE DATE NOT NULL
,   STATUS VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL
,   MODIFIED_AT TIMESTAMP(3) NOT NULL
,   COMPANY_KEY NUMBER NOT NULL
)
TABLESPACE TSD_COMPANY_DATA
LOGGING
;

CREATE UNIQUE INDEX EMPLOYEE_PK
    ON EMPLOYEE(EMPLOYEE_KEY)
    TABLESPACE TSD_COMPANY_IDX
;

CREATE UNIQUE INDEX EMPLOYEE_UK
    ON EMPLOYEE(COMPANY_KEY, EMPLOYEE_NO)
    TABLESPACE TSD_COMPANY_IDX
;

ALTER TABLE EMPLOYEE
    ADD CONSTRAINT EMPLOYEE_PK
        PRIMARY KEY (EMPLOYEE_KEY)
    USING INDEX EMPLOYEE_PK
;

CREATE TABLE SALARY(
    SALARY_KEY NUMBER NOT NULL
,   EMPLOYEE_KEY NUMBER NOT NULL
,   BASE_SALARY NUMBER(15, 0) NOT NULL
,   BONUS NUMBER(15, 0) NOT NULL
,   START_DATE DATE NOT NULL
,   END_DATE DATE
,   INPUT_TIME TIMESTAMP(3) NOT NULL
    /**
      한 행 자체의 날짜 정합성
     */
,   CONSTRAINT CK_SALARY_PERIOD CHECK(
        END_DATE IS NULL OR START_DATE <= END_DATE
    )
)
TABLESPACE TSD_SALARY_DATA
LOGGING
;

CREATE UNIQUE INDEX SALARY_PK
    ON SALARY(SALARY_KEY)
    TABLESPACE TSD_SALARY_IDX
;

/**
  같은 직원에게 동일 시작일 급여 이력 금지
 */
CREATE UNIQUE INDEX SALARY_UK
    ON SALARY(EMPLOYEE_KEY, START_DATE)
    TABLESPACE TSD_SALARY_IDX
;

/**
  직원당 현재 급여 1건
 */
CREATE UNIQUE INDEX SALARY_CURRENT_UK
    ON SALARY(
         CASE WHEN END_DATE IS NULL THEN EMPLOYEE_KEY END
    )
    TABLESPACE TSD_SALARY_IDX
;

ALTER TABLE SALARY
    ADD CONSTRAINT SALARY_PK
        PRIMARY KEY (SALARY_KEY)
    USING INDEX SALARY_PK
;

/******************************************************************************************
 SEQUENCE 정의: 모두 최대 10억 까지만.
******************************************************************************************/
CREATE SEQUENCE SEQ_COMPANY_KEY
    START WITH 1
    INCREMENT BY 1
    MAXVALUE 1000000000
    CACHE 20
    NOCYCLE
;

CREATE SEQUENCE SEQ_DEPARTMENT_KEY
    START WITH 1
    INCREMENT BY 1
    MAXVALUE 1000000000
    CACHE 20
    NOCYCLE
;

CREATE SEQUENCE SEQ_EMPLOYEE_KEY
    START WITH 1
    INCREMENT BY 1
    MAXVALUE 1000000000
    CACHE 20
    NOCYCLE
;

CREATE SEQUENCE SEQ_SALARY_KEY
    START WITH 1
    INCREMENT BY 1
    MAXVALUE 1000000000
    CACHE 20
    NOCYCLE
;
