SELECT EMPLOYEE_KEY, EMPLOYEE_NO, EMPLOYEE_NAME, MODIFIED_AT
FROM (
         SELECT e.EMPLOYEE_KEY, e.EMPLOYEE_NO, e.EMPLOYEE_NAME, e.MODIFIED_AT
         FROM EMPLOYEE e
         ORDER BY e.MODIFIED_AT DESC
     )
WHERE ROWNUM <= 1
;
